# Generated by Django 5.2 on 2025-05-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtModel',
            new_name='Art',
        ),
    ]
