# Generated by Django 5.2 on 2025-05-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_artmodel_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='image_url',
            new_name='image',
        ),
    ]
