# Generated by Django 5.2 on 2025-05-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_image_url_art_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
