# Generated by Django 5.2 on 2025-05-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_art_caption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art',
            new_name='Artwork',
        ),
    ]
