# Generated by Django 5.2 on 2025-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_art_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
