# Generated by Django 5.2 on 2025-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_artwork_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
