services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: 1
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        value: "https://galeri-misa.vercel.app"
